spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_prod
    username: sfg_prod_user
    password: 12345
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#                action: create
#                create-target: gutu_database_create.sql